"""
graph_engine.py — concept graph + adaptive sequencing for the literacy tutor.

Loads data/vocabulary.csv and builds a directed NetworkX graph where each
concept_id is a node and prereq_id defines a directed edge (prereq -> concept).
The graph drives an adaptive curriculum: a student is always shown the easiest
concept they are *ready* for (all prerequisites mastered) but have not mastered.

Public API (used by app.py):
    load_graph()
    get_next_concept(student_id)
    update_mastery(student_id, concept_id, correct_bool)
    get_student_progress(student_id)
"""

import os
from collections import deque

import pandas as pd
import networkx as nx

from . import db

VOCAB_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data", "vocabulary.csv")

_GRAPH = None  # cached graph (concepts change rarely; reload with force_reload=True)

# Columns expected in vocabulary.csv (generated by build_dataset.py).
#
# spoken_form is what the child is asked to SAY and what the scorer compares
# against. For a word it is just the word; for a letter it is the letter plus its
# anchor word ("ಅ ಅಮ್ಮ"), because an isolated letter is too short for the speech
# recogniser to hear. It is separate from kannada_word, which is what the card
# DISPLAYS — the child still sees, and is learning, the single letter.
_REQUIRED_COLUMNS = [
    "concept_id", "kannada_word", "tulu_word", "transliteration", "ipa",
    "english_meaning", "image_file", "category", "prereq_id", "difficulty",
    "level", "spoken_form", "anchor_word", "phrase_gloss",
]

# The three explicit syllabus tiers, in order, for grouping and display. A
# concept's `level` is written by build_dataset.py; the serving order (driven by
# difficulty in get_next_concept) already runs Basic -> Intermediate -> Advanced.
LEVELS = ["Basic", "Intermediate", "Advanced"]


def load_graph(force_reload=False):
    """Build and return the concept DiGraph from vocabulary.csv (cached)."""
    global _GRAPH
    if _GRAPH is not None and not force_reload:
        return _GRAPH

    if not os.path.exists(VOCAB_PATH):
        raise FileNotFoundError(f"vocabulary CSV not found at {VOCAB_PATH}")

    # dtype=str + keep_default_na=False so empty prereq_id stays "" (not NaN).
    df = pd.read_csv(VOCAB_PATH, dtype=str, encoding="utf-8", keep_default_na=False)

    missing = [c for c in _REQUIRED_COLUMNS if c not in df.columns]
    if missing:
        raise ValueError(f"vocabulary.csv is missing columns: {missing}")

    G = nx.DiGraph()

    # First pass: add every node so edges can reference any concept.
    for _, row in df.iterrows():
        cid = row["concept_id"].strip()
        if not cid:
            continue
        if cid in G:
            raise ValueError(f"duplicate concept_id in vocabulary.csv: {cid}")
        difficulty = row["difficulty"].strip()
        try:
            difficulty = int(difficulty) if difficulty else 99
        except ValueError:
            raise ValueError(
                f"concept '{cid}' has a non-numeric difficulty: {difficulty!r} "
                "(fix vocabulary.csv — run validate_dataset.py)"
            ) from None
        kannada_word = row["kannada_word"].strip()
        G.add_node(
            cid,
            concept_id=cid,
            kannada_word=kannada_word,
            tulu_word=row["tulu_word"].strip(),
            transliteration=row["transliteration"].strip(),
            ipa=row["ipa"].strip(),
            english_meaning=row["english_meaning"].strip(),
            image_file=row["image_file"].strip(),
            category=row["category"].strip(),
            difficulty=difficulty,
            # The syllabus tier (Basic / Intermediate / Advanced). Falls back to
            # Basic if a hand-edited CSV predates the column, so the app still runs.
            level=row["level"].strip() or "Basic",
            # Fall back to the displayed word so a hand-edited CSV that predates
            # the spoken_form column still scores instead of crashing.
            spoken_form=row["spoken_form"].strip() or kannada_word,
            anchor_word=row["anchor_word"].strip(),
            phrase_gloss=row["phrase_gloss"].strip(),
        )

    # Second pass: add prereq -> concept edges.
    for _, row in df.iterrows():
        cid = row["concept_id"].strip()
        prereq = row["prereq_id"].strip()
        if not cid or not prereq:
            continue
        if prereq not in G:
            raise ValueError(
                f"prereq_id '{prereq}' (for concept '{cid}') is not a known concept_id"
            )
        G.add_edge(prereq, cid)

    if not nx.is_directed_acyclic_graph(G):
        cycle = nx.find_cycle(G)
        raise ValueError(f"vocabulary prerequisites contain a cycle: {cycle}")

    _GRAPH = G
    return G


def concept_info(concept_id):
    """Return the attribute dict for one concept, or None if unknown."""
    G = load_graph()
    return dict(G.nodes[concept_id]) if concept_id in G else None


# A concept a child has attempted this many times without mastering is "parked":
# it stops being served, and it stops blocking what comes after it.
#
# Without this the tutor can trap a child forever. get_next_concept() always
# returns the lowest (difficulty, id) concept that is ready and unmastered — so a
# concept the child cannot master is returned again, and again, and again, and
# nothing else in the curriculum is ever reachable. That is not hypothetical:
# three real words (ತಲೆ, ಎಲೆ, ಕೈ) are short enough that the recogniser reliably
# mishears them, and the very first version of this curriculum opened on a bare
# ಅ that could never be recognised at all.
#
# Those particular cases are fixed in the dataset. This is the safety net for the
# ones that are not: a child with an unusual voice, a bad microphone, a word this
# model happens to hate. A parked concept counts as *passed for progression* (the
# child moves on) but never as *mastered* (the score stays honest), and it is
# surfaced to the teacher under "Needs help" — which is exactly what a human
# teacher does with a child stuck on one word.
PARK_AFTER_ATTEMPTS = 6


def _progression_sets(student_id, G):
    """(mastered, parked) — parked = tried hard, still failing, moved past."""
    mastered, parked = set(), set()
    for row in db.get_mastery_rows(student_id):
        cid = row["concept_id"]
        if cid not in G:  # a concept dropped from the CSV; ignore the stale row
            continue
        if row["mastery_score"] >= db.MASTERY_THRESHOLD:
            mastered.add(cid)
        elif row["attempts"] >= PARK_AFTER_ATTEMPTS:
            parked.add(cid)
    return mastered, parked


def get_next_concept(student_id):
    """
    The concept the student should learn next: the lowest-difficulty concept that
    is not yet mastered, not parked, and whose prerequisites are all cleared.
    Returns None when nothing is left.
    """
    G = load_graph()
    mastered, parked = _progression_sets(student_id, G)
    # Prerequisites are satisfied by mastering a concept OR by having genuinely
    # tried and been parked on it. Otherwise one unrecognisable letter would lock
    # the entire rest of the alphabet behind it.
    cleared = mastered | parked

    visited = set()
    queue = deque()

    # Entry points: root concepts, plus everything just past a cleared concept.
    for n in G.nodes:
        if G.in_degree(n) == 0:
            queue.append(n)
    for n in cleared:
        queue.extend(G.successors(n))

    candidates = []
    while queue:
        node = queue.popleft()
        if node in visited:
            continue
        visited.add(node)

        if node in cleared:
            # Done with (or parked on) this one — walk past it to what it unlocks.
            queue.extend(G.successors(node))
            continue

        if all(p in cleared for p in G.predecessors(node)):
            candidates.append(node)
        # else: locked — a prerequisite has not been cleared yet.

    if not candidates:
        return None

    # Easiest first; ties broken by concept_id so the order is deterministic.
    candidates.sort(key=lambda n: (G.nodes[n]["difficulty"], n))
    return dict(G.nodes[candidates[0]])


def update_mastery(student_id, concept_id, correct_bool, raw_score=None, heard=None):
    """Record an attempt and return the updated mastery score.

    `raw_score` (optional, 0..1) is the pronunciation similarity for this
    attempt; it is logged in the session history for the teacher view.
    `heard` (optional) is what the recogniser transcribed, logged so the teacher
    can see the child's actual error rather than only its score.
    """
    return db.update_mastery(student_id, concept_id, correct_bool, raw_score, heard)


def get_student_progress(student_id):
    """
    Full progress view: every concept enriched with the student's mastery.
    Concepts never attempted appear with score 0 / attempts 0. Sorted by
    (difficulty, concept_id) so it reads as a curriculum.
    """
    G = load_graph()
    rows = {r["concept_id"]: r for r in db.get_mastery_rows(student_id)}

    progress = []
    for cid in G.nodes:
        node = G.nodes[cid]
        r = rows.get(cid)
        score = r["mastery_score"] if r else 0.0
        attempts = r["attempts"] if r else 0
        mastered = score >= db.MASTERY_THRESHOLD
        progress.append(
            {
                "concept_id": cid,
                "kannada_word": node["kannada_word"],
                "tulu_word": node["tulu_word"],
                "transliteration": node["transliteration"],
                "english_meaning": node["english_meaning"],
                "category": node["category"],
                "difficulty": node["difficulty"],
                "level": node.get("level", "Basic"),
                "mastery_score": round(score, 4),
                "attempts": attempts,
                "mastered": mastered,
                # Tried repeatedly and still not mastered: the tutor has moved
                # the child on, and a human needs to look at this one.
                "parked": (not mastered) and attempts >= PARK_AFTER_ATTEMPTS,
                "last_seen": r["last_seen"] if r else None,
            }
        )
    progress.sort(key=lambda p: (p["difficulty"], p["concept_id"]))
    return progress


def mastery_summary(student_id):
    """Return (mastered_count, total_count) for progress display."""
    progress = get_student_progress(student_id)
    mastered = sum(1 for p in progress if p["mastered"])
    return mastered, len(progress)


def mastery_by_level(student_id):
    """
    Per-tier progress: {level: (mastered, total)} for the three syllabus tiers,
    in Basic -> Intermediate -> Advanced order. Lets the UI show the leveled
    progression explicitly rather than as one flat bar.
    """
    progress = get_student_progress(student_id)
    out = {lv: [0, 0] for lv in LEVELS}
    for p in progress:
        lv = p.get("level") or "Basic"
        out.setdefault(lv, [0, 0])
        out[lv][1] += 1
        if p["mastered"]:
            out[lv][0] += 1
    return {lv: (m, t) for lv, (m, t) in out.items()}
