[theme]
base = "light"
primaryColor = "#17150F"
backgroundColor = "#FBFAF6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#3A362C"
font = "sans serif"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = false

[server]
maxUploadSize = 5
